services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python3 app.py
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:17.0-bullseye
    # postgres:17.0-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_face_reg:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=user@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=root'
      - 'PGADMIN_LOG_LEVEL=ERROR'
    depends_on:
      - db
    ports:
      - "16543:80"
    volumes:
      - postgres_data_valdin:/pgadmin4/data 
      - ./servers1.json:/pgadmin4/servers.json
    # restart: always

volumes:
  postgres_data_valdin: